import React from 'react'
import CommanHeader from '../../components/CommanHeader';

const AboutDetails = () => {
  return (
    <div className="w-full h-screen flex flex-col bg-[#242424] text-white">
      <CommanHeader title="Confidentiality Agreement" />
      <div className="w-full max-w-[450px] flex-1 mx-auto scrollbar-hide overflow-y-auto px-4 py-6 mt-12">
        <div className="space-y-6 text-sm leading-relaxed">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use 
            and disclosure of Your information when You use the Service and tells You about 
            Your privacy rights and how the law protects You.
          </p>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Interpretation and Definitions</h2>
            
            <h3 className="text-base font-medium mb-2 text-gray-300">Interpretation</h3>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the 
              following conditions. The following definitions shall have the same meaning regardless 
              of whether they appear in singular or in plural.
            </p>

            <h3 className="text-base font-medium mb-2 text-gray-300">Definitions</h3>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            
            <div className="space-y-3 ml-4">
              <p><span className="font-medium text-gray-300">You</span> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
              
              <p><span className="font-medium text-gray-300">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to strikegame.</p>
              
              <p><span className="font-medium text-gray-300">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              
              <p><span className="font-medium text-gray-300">Account</span> means a unique account created for You to access our Service or parts of our Service.</p>
              
              <p><span className="font-medium text-gray-300">Website</span> refers to strike game, accessible from: https://strikegame.live</p>
              
              <p><span className="font-medium text-gray-300">Service</span> refers to the Website.</p>
              
              <p><span className="font-medium text-gray-300">Country</span> refers to: India</p>
              
              <p><span className="font-medium text-gray-300">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used.</p>
              
              <p><span className="font-medium text-gray-300">Third-party social media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
              
              <p><span className="font-medium text-gray-300">Personal Data</span> is any information that relates to an identified or identifiable individual.</p>
              
              <p><span className="font-medium text-gray-300">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              
              <p><span className="font-medium text-gray-300">Device</span> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
              
              <p><span className="font-medium text-gray-300">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-base font-medium mb-2 text-gray-300">Types of Data Collected</h3>
            
            <h4 className="font-medium mb-2 text-gray-400">Personal Data</h4>
            <p className="mb-3">
              While using Our Service, we may ask You to provide Us with certain personally 
              identifiable information that can be used to contact or identify You. Personally 
              identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc ml-6 mb-4 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="font-medium mb-2 text-gray-400">Usage Data</h4>
            <p className="mb-3">Usage Data is collected automatically when using the Service.</p>
            <p className="mb-3">
              Usage Data may include information such as Your Device's Internet Protocol 
              address (e.g. IP address), browser type, browser version, the pages of Our Service 
              that You visit, the time and date of Your visit, the time spent on those pages, unique 
              device identifiers and other diagnostic data.
            </p>
            <p className="mb-3">
              When You access the Service by or through a mobile device, we may collect certain 
              information automatically, including, but not limited to, the type of mobile device You 
              use, your mobile device unique ID, the IP address of Your mobile device, your mobile 
              operating system, the type of mobile Internet browser You use, unique device 
              identifiers and other diagnostic data.
            </p>
            <p className="mb-4">
              We may also collect information that Your browser sends whenever You visit our 
              Service or when You access the Service by or through a mobile device.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Tracking Technologies and Cookies</h2>
            <p className="mb-3">
              We use Cookies and similar tracking technologies to track the activity on Our Service 
              and store certain information. Tracking technologies used are beacons, tags, and 
              scripts to collect and track information and to improve and analyse Our Service.
            </p>
            <p className="mb-3">
              You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is 
              being sent. However, if You do not accept Cookies, you may not be able to use some 
              parts of our Service.
            </p>
            <p className="mb-4">
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on 
              your personal computer or mobile device when You go offline, while Session Cookies 
              are deleted as soon as You close your web browser.
            </p>
            <p className="mb-3">We use both session and persistent Cookies for the purposes set out below:</p>

            <div className="space-y-4 ml-4">
              <div>
                <h4 className="font-medium mb-2 text-gray-400">Necessary / Essential Cookies</h4>
                <p className="mb-1"><span className="font-medium text-gray-300">Type:</span> Session Cookies</p>
                <p className="mb-1"><span className="font-medium text-gray-300">Administered by:</span> Us</p>
                <p className="mb-2"><span className="font-medium text-gray-300">Purpose:</span> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid having to re-enter your preferences every time You use the Website.</p>
              </div>

              <div>
                <h4 className="font-medium mb-2 text-gray-400">Cookies Policy / Notice Acceptance Cookies</h4>
                <p className="mb-1"><span className="font-medium text-gray-300">Type:</span> Persistent Cookies</p>
                <p className="mb-1"><span className="font-medium text-gray-300">Administered by:</span> Us</p>
                <p className="mb-2"><span className="font-medium text-gray-300">Purpose:</span> These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </div>

              <div>
                <h4 className="font-medium mb-2 text-gray-400">Functionality Cookies</h4>
                <p className="mb-1"><span className="font-medium text-gray-300">Type:</span> Persistent Cookies</p>
                <p className="mb-1"><span className="font-medium text-gray-300">Administered by:</span> Us</p>
                <p className="mb-2"><span className="font-medium text-gray-300">Purpose:</span> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
              </div>
            </div>
            <p className="mt-3">
              For more information about the cookies we use and your choices regarding cookies, 
              please visit our Cookies Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Use of Your Personal Data</h2>
            <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc ml-6 mb-4 space-y-2">
              <li><span className="font-medium text-gray-300">To provide and maintain our Service,</span> including to monitor the usage of our Service.</li>
              <li><span className="font-medium text-gray-300">To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
              <li><span className="font-medium text-gray-300">For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li><span className="font-medium text-gray-300">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
              <li><span className="font-medium text-gray-300">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
              <li><span className="font-medium text-gray-300">To manage Your requests:</span> To attend and manage Your requests to Us.</li>
            </ul>

            <p className="mb-3">We may share your personal information in the following situations:</p>
            <ul className="list-disc ml-6 mb-4 space-y-2">
              <li><span className="font-medium text-gray-300">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyse the use of our Service, to contact You.</li>
              <li><span className="font-medium text-gray-300">For Business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
              <li><span className="font-medium text-gray-300">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
              <li><span className="font-medium text-gray-300">With Business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
              <li><span className="font-medium text-gray-300">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Retention of Your Personal Data</h2>
            <p className="mb-3">
              The Company will retain Your Personal Data only for as long as is necessary for the 
              purposes set out in this Privacy Policy. We will retain and use Your Personal Data to 
              the extent necessary to comply with our legal obligations (for example, if we are 
              required to retain your data to comply with applicable laws), resolve disputes, and 
              enforce our legal agreements and policies.
            </p>
            <p className="mb-4">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data 
              is generally retained for a shorter period of time, except when this data is used to 
              strengthen the security or to improve the functionality of Our Service, or We are 
              legally obligated to retain this data for longer time periods.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Transfer of Your Personal Data</h2>
            <p className="mb-3">
              Your information, including Personal Data, is processed at the Company's operating 
              offices and in any other places where the parties involved in the processing are 
              located. It means that this information may be transferred to — and maintained on — 
              computers located outside of Your state, province, country or other governmental 
              jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>
            <p className="mb-3">
              Your consent to this Privacy Policy followed by Your submission of such information 
              represents Your agreement to that transfer.
            </p>
            <p className="mb-4">
              The Company will take all steps reasonably necessary to ensure that Your data is 
              treated securely and in accordance with this Privacy Policy and no transfer of Your 
              Personal Data will take place to an organization or a country unless there are 
              adequate controls in place including the security of Your data and other personal information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Disclosure of Your Personal Data</h2>
            
            <h3 className="text-base font-medium mb-2 text-gray-300">Business Transactions</h3>
            <p className="mb-4">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data 
              may be transferred. We will provide notice before Your Personal Data is transferred 
              and becomes subject to a different Privacy Policy.
            </p>

            <h3 className="text-base font-medium mb-2 text-gray-300">Law enforcement</h3>
            <p className="mb-4">
              Under certain circumstances, the Company may be required to disclose Your Personal 
              Data if required to do so by law or in response to valid requests by public authorities 
              (e.g. a court or a government agency).
            </p>

            <h3 className="text-base font-medium mb-2 text-gray-300">Legal requirements</h3>
            <p className="mb-3">
              The Company may disclose Your Personal Data in the good faith belief that such 
              action is necessary to:
            </p>
            <ul className="list-disc ml-6 mb-4 space-y-1">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Security of Your Personal Data</h2>
            <p className="mb-4">
              The security of Your Personal Data is important to Us, but remember that no method 
              of transmission over the Internet, or method of electronic storage is 100% secure. 
              While We strive to use commercially acceptable means to protect Your Personal Data, 
              we cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Children's Privacy</h2>
            <p className="mb-3">
              Our Service does not address anyone under the age of 13. We do not knowingly 
              collect personally identifiable information from anyone under the age of 13. If We 
              become aware that We have collected Personal Data from anyone under the age of 13 
              without verification of parental consent, we take steps to remove that information 
              from Our servers.
            </p>
            <p className="mb-4">
              If We need to rely on consent as a legal basis for processing Your information and 
              Your country requires consent from a parent, we may require Your parent's consent 
              before We collect and use that information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Links to Other Websites</h2>
            <p className="mb-3">
              Our Service may contain links to other websites that are not operated by Us. If You 
              click on a third-party link, you will be directed to that third party's site. We strongly 
              advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="mb-4">
              We have no control over and assume no responsibility for the content, privacy 
              policies or practices of any third-party sites or services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Changes to this Privacy Policy</h2>
            <p className="mb-3">
              We will update our Privacy Policy from time to time. We will notify You of any 
              changes by posting the new Privacy Policy on this page.
            </p>
            <p className="mb-3">
              We will let You know via email and/or a prominent notice on Our Service, prior to the 
              change becoming effective and update the "Last updated" date at the top of this 
              Privacy Policy.
            </p>
            <p className="mb-4">
              You are advised to review this Privacy Policy periodically for any changes. Changes 
              to this Privacy Policy are effective when they are posted on this page.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-[#d9ac4f]">Contact Us</h2>
            <p className="mb-2">If you have any questions about this Privacy Policy, you can contact us:</p>
            <p>By visiting this page on our website: <span className="text-[#d9ac4f]">https://strikegame.live</span></p>
          </section>
        </div>
      </div>
    </div>
  );
}

export default AboutDetails